### ISSUE TITLE
Background Thread Support

### ISSUE THREAD

**Issue by bawelter** [fluttercouch/fluttercouch#13]
Need to look into running operations on background process to improve performance.

**Comment by bawelter** [comment]
So did some research and looks like the main culprits in performance his will be the execute and query change listener so I put those on an async thread and it seemed to boost the performance.  Most likely will need to test this some more but seems like it is working fine.

**Comment by bawelter** [comment]
This was added here: 3d4a10fb23f4312487dcb7bb353b6d331fd8ead3

**Comment by phattranky** [comment]
Can you help to add document regarding using Background Thread. @bawelter

**Comment by bawelter** [comment]
@phattranky the same background thread is used by default for all query change listeners to prevent any performance issues with running it on the main thread. All results are then posted on the main thread as it is required.  Does that answer your question?  I didn't see a need to make it any more involved than this at the moment.

**Comment by phattranky** [comment]
@bawelter Thanks for your quick response. So We just using like usual. Because I just concern it still has some delay when I query the Document (it's freeze my UI about 1 - 2s). My function below.

```
static Future<PaginationResultModel> getLstMyWordAsWordModelPagination({
    int page = 1,
    int length = 100
  }) async {
    Document lstMyWordDoc = await getDataWithId(getMyWordKey());
    final List<WordModel> result = new List();

    final mapLstMyWordDoc = lstMyWordDoc.toMap();
    final getFrom = (page - 1) * length;

    // From Exceed list
    if (getFrom > mapLstMyWordDoc.length) {
      return PaginationResultModel(
        data: [],
        page: page,
        totalItemsPerPage: length,
        total: mapLstMyWordDoc.length
      ); 
    }

    List<MyWordModel> processingLstMyWord = (mapLstMyWordDoc.values.toList().map<MyWordModel>(
      (item) => MyWordModel.fromMap(item)
    ).toList());
    processingLstMyWord.sort((a, b) => a.createdDate != null ? a.createdDate.compareTo(b.createdDate != null ? b.createdDate : DateTime.now().millisecondsSinceEpoch) : 0);

    if (getFrom + length > processingLstMyWord.length) {
      processingLstMyWord = processingLstMyWord.getRange(getFrom, processingLstMyWord.length).toList();
    } else {
      processingLstMyWord = processingLstMyWord.getRange(getFrom, getFrom + length).toList();
    }

    Document lstWordDoc = await getDataWithId(getWordKey());
    processingLstMyWord.forEach((MyWordModel myWord) {
      final wordModel = WordModel.fromMap(lstWordDoc.getMap(myWord.id));
      wordModel.linkedMyWord = myWord;

      result.add(wordModel);
    });

    return PaginationResultModel(
      data: result,
      page: page,
      totalItemsPerPage: length,
      total: mapLstMyWordDoc.length
    );
  }
```

**Comment by phattranky** [comment]
My `pubspec`

```
fluttercouch:
    git: 
      url: git://github.com/oltrenuovefrontiere/fluttercouch
```

**Comment by bawelter** [comment]
@phattranky you are calling the function getDocumentWithId this doesn't use the query implementation which executes on the background thread.  Try using the query implementation executing a single query and then loop through the results.  This should give you better results.  Please let me know if you have any other questions or have trouble with how to do this.

**Comment by bawelter** [comment]
My guess is that the following loop is actually what is taking 2-3s.

```
    processingLstMyWord.forEach((MyWordModel myWord) {
      final wordModel = WordModel.fromMap(lstWordDoc.getMap(myWord.id));
      wordModel.linkedMyWord = myWord;

      result.add(wordModel);
    });
```

Try printing out some execution times to see how long each code block is taking.

**Comment by phattranky** [comment]
@bawelter Many thanks for your support.

Can I ask one more question? . How to using `query`. I only see the `get document with id`

```
 Try using the query implementation executing a single query
```

**Comment by bawelter** [comment]
@phattranky please refer to the Swift sdk the fluttercouch uses the same syntax.  https://docs.couchbase.com/mobile/2.5.0/couchbase-lite-swift/

**Comment by phattranky** [comment]
Many thanks. I will check it
