### ISSUE TITLE
NPE when Replication Event listener invoked

### ISSUE THREAD

**Issue by specdout** [fluttercouch/fluttercouch#23]
Thanks very much for writing Fluttercouch! I'm encountering the following issue, no doubt a result of my unfamiliarity with Flutter and Dart :)

**Describe the bug**
A NullPointerException is encountered in low-level code when the framework attempts to call the Replication Event handler. The stack trace produced is

`E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): Failed to open event stream
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): java.lang.NullPointerException: Attempt to invoke virtual method 'com.couchbase.lite.ListenerToken com.couchbase.lite.Replicator.addChangeListener(com.couchbase.lite.ReplicatorChangeListener)' on a null object reference
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at it.oltrenuovefrontiere.fluttercouch.ReplicationEventListener.onListen(ReplicationEventListener.java:26)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:193)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at android.os.Looper.loop(Looper.java:181)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/EventChannel#it.oltrenuovefrontiere.fluttercouch/replicationEventChannel(31747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

**To Reproduce**
Initialize an instance of the local 'Database' class and then invoke initDatabase() on the instance. The Database class is defined as follows:

`import 'package:fluttercouch/fluttercouch.dart';
import 'package:mms/src/constants.dart';

class Database with Fluttercouch {
  String _database;

  Database();

  // initDatabase must be called explicitly!
  initDatabase() async {
    try {
      print("initializing database...");
      var db = await initDatabaseWithName(DATABASE_NAME);
      this._database = db;
      print("initializing replication...");
      setReplicatorEndpoint(REPLICATION_URL);
      setReplicatorType(REPLICATION_TYPE);
      setReplicatorBasicAuthentication(<String, String>{
        "username": REPLICATION_USER,
        "password": REPLICATION_PASSWORD
      });
      setReplicatorContinuous(true);
      listenReplicationEvents(this.handleReplicationEvent);
      initReplicator();
      startReplicator();
      print("database initialization complete!");
    } on Exception catch (e) {
      print("error: could not initialize database - $e");
    }
  }

  void handleReplicationEvent(dynamic replicationEvent) {
    switch (replicationEvent) {
      case ("BUSY"):
      // executed when the replicator status changes to BUSY
      case ("IDLE"):
      // executed when the replicator status changes to IDLE
      case ("OFFLINE"):
      // executed when the replicator status changes to OFFLINE
      case ("STOPPED"):
      // executed when the replicator status changes to STOPPED
      case ("CONNECTING"):
      // executed when the replicator status changes to CONNECTING
    }
  }
}`

**Expected behavior**
Replication Events are reported by the handler.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Fluttercouch: 0.5.0
 - Flutter: v1.7.8+hotfix.4

**Comment by specdout** [comment]
Figured this one out: it actually makes a difference to not attempt to init the Replicator until configuration is complete <sigh>.  In the code above, you'll notice that I'm setting the replication event handler function _before_ I initialize the Replicator. Unlike other aspects of the Replicator configuration, the event handler is set directly on the Replicator instance, the latter not being created until 'initReplicator()' is called. In other words, order is important here :)

**Comment by oltrenuovefrontiere** [comment]
Hi @specdout,
yes, I confirm you that the the replicator must be initiliazed before registering any event handler.

Thank you for sharing with us your issue and your solution. I'll add a note in the documentation to state that requirement and we'll handle better this error in the code itself.

Regards,
Luca

**Comment by specdout** [comment]
Thanks very much for your response, Luca :))

Ron

**Comment by richard457** [comment]
Can you help me understaning addChangeListener on Query? thank you in advance.
