### ISSUE TITLE
Can we have example of how to run query?

### ISSUE THREAD

**Issue by richard457** [fluttercouch/fluttercouch#27]
First of all thank you for the plugin, I have a problem of making query work in my app could you help us understanding on how to run a simple query thank you.

**Comment by richard457** [comment]
for example how Can I run this query: SELECT * FROM `bucket` WHERE _id="users";

**Comment by oltrenuovefrontiere** [comment]
@richard457 The syntax is similar to the one presented here: https://docs.couchbase.com/couchbase-lite/2.7/java-android.html#query

I'm currently out of office, but I'll be glad to send you the example you requested asap

**Comment by richard457** [comment]
Thank you so much I am waiting thank you once again.

**Comment by oltrenuovefrontiere** [comment]
The syntax is the following if you have a property "_id" inside the document
```dart
Query query = QueryBuilder.select([SelectResult.all()])
      .from("bucket")
      .where(Expression.property("_id").equalTo(Expression.string("users")));
```

The syntax is the following instead if you want to match based upon the id of the document (your N1QL query should have been WHERE meta().id = "users")
```dart
Query query = QueryBuilder.select([SelectResult.all()])
      .from("bucket")
      .where(Meta.id.equalTo(Expression.string("users")));
```

**Comment by richard457** [comment]
Do I need to call ` query.execute();
      query.addChangeListener((change) => {
            // if(change.results != null)
            //   {
            print(change.results)
            //resultsCallback(change.results);
            // }
          });` to get query result?

**Comment by richard457** [comment]
addChangeListener is not getting trigerred on the above query: here is my final code ` Query query = QueryBuilder.select([SelectResult.all()])
          .from("lagrace")
          .where(
              Expression.property("_id").equalTo(Expression.string("users")));

      query.execute();
      query.addChangeListener((change) => {
            // if(change.results != null)
            //   {
            print(change.results)
            //resultsCallback(change.results);
            // }
          });`

**Comment by richard457** [comment]
![couchbase](https://user-images.githubusercontent.com/8529700/75453126-187ec780-597c-11ea-99b3-d575f9e5a5ab.PNG) you can see my data on the above screenShoot.

**Comment by richard457** [comment]
![couchbase](https://user-images.githubusercontent.com/8529700/75453242-4b28c000-597c-11ea-8805-92d08e2bcba7.PNG)
you can see the attached screenshoot.

**Comment by oltrenuovefrontiere** [comment]
To get the results you have to await for them in an async method in this way:
```dart
ResultSet resultset = await query.execute();
```
OR use the .then function on the returned Future
```dart
query.execute().then((resultSet) => {
   // Your code goes here
});
```

**Comment by richard457** [comment]
Sorry to frustrate you, I am new to this amazing library, how to get actual data tried something like
 `resultset.forEach((element) {
        print(element);
      });`

but I am getting `Instance of 'Result'` how to get actual result any idea, thanks for help.

**Comment by richard457** [comment]
> To get the results you have to await for them in an async method in this way:
> 
> ```dart
> ResultSet resultset = await query.execute();
> ```
> 
> OR use the .then function on the returned Future
> 
> ```dart
> query.execute().then((resultSet) => {
>    // Your code goes here
> });
> ```

Any idea of how to loop and get data?

**Comment by richard457** [comment]
how to delete document from local and online or simple delete is there option? here is reference https://docs.couchbase.com/mobile/2.1/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC13purgeDocumentyAA0F0CKF
