### ISSUE TITLE
flutter desktop windows

### ISSUE THREAD

**Issue by 926** [fluttercouch/fluttercouch#33]
Hi all,
Thanks and congratulations for bringing couchbase to flutter,

**Describe the solution you'd like**
What would it take to use a local couchbase db on a Flutter Desktop / windows app ?

**Describe alternatives you've considered**
I currently use sembastdb and sync using mongodb

**Comment by bawelter** [comment]
You need to rewrite the entire thing using interop.  This is because I don’t believe there is a native platform solution for couchbase lite for these platforms.

**Comment by 926** [comment]
Thank you for your quick reply,
I'll stick to current config then.
